import { DEFAULT_RECOMMENDATION_WEIGHTS } from "@/lib/constants";
import type { CandidateCourse, EngineOptions, LearnerContext } from "@/lib/recommendation/types";

/**
 * A miniature catalog that mirrors the shape of the seeded one: foundations,
 * a prompting course, one role module per family, the two mandatory internal
 * courses, and a technical track.
 */
export function course(partial: Partial<CandidateCourse> & { id: string }): CandidateCourse {
  return {
    code: partial.id.toUpperCase(),
    title: partial.id,
    slug: partial.id,
    providerName: "Test Provider",
    providerTrust: 0.9,
    platform: "Test",
    estimatedHours: 6,
    difficulty: "BEGINNER",
    language: "en",
    subtitleLanguages: [],
    levelCode: "L1",
    status: "PUBLISHED",
    linkWorking: true,
    stillAvailable: true,
    isInternal: false,
    isTechnical: false,
    isMandatory: false,
    certificateAvailable: true,
    qualityScore: 0.85,
    rating: 4.6,
    feedbackScore: null,
    competencies: [{ key: "FUNDAMENTALS", weight: 3 }],
    departmentIds: [],
    jobFamilies: [{ jobFamily: "GENERAL", weight: 1 }],
    goals: [],
    prerequisiteIds: [],
    ...partial,
  };
}

export const CATALOG: CandidateCourse[] = [
  course({
    id: "ai-for-everyone",
    estimatedHours: 6,
    levelCode: "L0",
    competencies: [{ key: "FUNDAMENTALS", weight: 3 }],
    goals: [{ goalKey: "RESEARCH", weight: 1 }],
  }),
  course({
    id: "generative-ai",
    estimatedHours: 6,
    levelCode: "L1",
    competencies: [
      { key: "FUNDAMENTALS", weight: 1 },
      { key: "WORKPLACE", weight: 3 },
    ],
    goals: [{ goalKey: "WRITING", weight: 1 }],
    prerequisiteIds: ["ai-for-everyone"],
  }),
  course({
    id: "prompting-essentials",
    estimatedHours: 9,
    levelCode: "L1",
    competencies: [{ key: "PROMPTING", weight: 4 }],
    goals: [
      { goalKey: "WRITING", weight: 2 },
      { goalKey: "EMAIL", weight: 2 },
      { goalKey: "REPORTS", weight: 2 },
    ],
  }),
  course({
    id: "prompt-engineering-advanced",
    estimatedHours: 18,
    levelCode: "L2",
    difficulty: "INTERMEDIATE",
    competencies: [{ key: "PROMPTING", weight: 4 }],
    goals: [{ goalKey: "AUTOMATION", weight: 2 }],
  }),
  course({
    id: "ai-for-finance",
    estimatedHours: 8,
    levelCode: "L2",
    isInternal: true,
    providerTrust: 1,
    qualityScore: 1,
    competencies: [
      { key: "WORKPLACE", weight: 4 },
      { key: "DATA_AUTOMATION", weight: 1 },
    ],
    departmentIds: ["dept-fin"],
    jobFamilies: [{ jobFamily: "FINANCE", weight: 3 }],
    goals: [
      { goalKey: "EXCEL", weight: 3 },
      { goalKey: "REPORTS", weight: 3 },
    ],
  }),
  course({
    id: "ai-for-hr",
    estimatedHours: 8,
    levelCode: "L2",
    isInternal: true,
    providerTrust: 1,
    qualityScore: 1,
    competencies: [{ key: "WORKPLACE", weight: 4 }],
    departmentIds: ["dept-hr"],
    jobFamilies: [{ jobFamily: "HR", weight: 3 }],
    goals: [{ goalKey: "WRITING", weight: 3 }],
  }),
  course({
    id: "ai-for-production",
    estimatedHours: 8,
    levelCode: "L2",
    isInternal: true,
    providerTrust: 1,
    qualityScore: 1,
    competencies: [{ key: "WORKPLACE", weight: 4 }],
    departmentIds: ["dept-prd"],
    jobFamilies: [{ jobFamily: "PRODUCTION", weight: 3 }],
    goals: [{ goalKey: "PRODUCTION_IMPROVEMENT", weight: 3 }],
  }),
  course({
    id: "ai-for-management",
    estimatedHours: 7,
    levelCode: "L2",
    isInternal: true,
    providerTrust: 1,
    qualityScore: 1,
    competencies: [{ key: "WORKPLACE", weight: 4 }],
    departmentIds: ["dept-mgt"],
    jobFamilies: [{ jobFamily: "MANAGEMENT", weight: 3 }],
    goals: [{ goalKey: "DECISION_MAKING", weight: 3 }],
  }),
  course({
    id: "ai-at-tc",
    estimatedHours: 5,
    levelCode: "L0",
    isInternal: true,
    isMandatory: true,
    providerTrust: 1,
    qualityScore: 1,
    competencies: [
      { key: "WORKPLACE", weight: 3 },
      { key: "PROMPTING", weight: 2 },
    ],
  }),
  course({
    id: "responsible-ai",
    estimatedHours: 4,
    levelCode: "L1",
    isInternal: true,
    isMandatory: true,
    providerTrust: 1,
    qualityScore: 1,
    competencies: [{ key: "RESPONSIBLE_AI", weight: 5 }],
  }),
  course({
    id: "ml-for-everybody",
    estimatedHours: 7,
    levelCode: "L4",
    isTechnical: true,
    difficulty: "ADVANCED",
    competencies: [{ key: "TECHNICAL", weight: 4 }],
    jobFamilies: [{ jobFamily: "IT", weight: 2 }],
    goals: [{ goalKey: "PROGRAMMING", weight: 2 }],
  }),
  course({
    id: "ai-for-it",
    estimatedHours: 9,
    levelCode: "L3",
    isInternal: true,
    isTechnical: true,
    difficulty: "ADVANCED",
    providerTrust: 1,
    qualityScore: 1,
    competencies: [
      { key: "TECHNICAL", weight: 4 },
      { key: "DATA_AUTOMATION", weight: 2 },
    ],
    departmentIds: ["dept-it"],
    jobFamilies: [{ jobFamily: "IT", weight: 3 }],
    goals: [
      { goalKey: "PROGRAMMING", weight: 3 },
      { goalKey: "AUTOMATION", weight: 3 },
    ],
  }),
  course({
    id: "archived-course",
    status: "ARCHIVED",
    competencies: [{ key: "FUNDAMENTALS", weight: 1 }],
  }),
  course({
    id: "dead-link-course",
    linkWorking: false,
    competencies: [{ key: "FUNDAMENTALS", weight: 1 }],
  }),
];

export const PATH_TEMPLATES: NonNullable<EngineOptions["pathTemplates"]> = [
  {
    id: "path-foundation",
    code: "PATH-FOUNDATION",
    title: "AI Productivity Foundation",
    audienceLevel: "L0",
    isTechnical: false,
    jobFamilies: [],
    targetLevelCode: "L2",
  },
  {
    id: "path-practitioner",
    code: "PATH-PRACTITIONER",
    title: "AI Practitioner Pathway",
    audienceLevel: "L2",
    isTechnical: false,
    jobFamilies: [],
    targetLevelCode: "L3",
  },
  {
    id: "path-technical",
    code: "PATH-TECHNICAL",
    title: "AI Builder Technical Pathway",
    audienceLevel: "L3",
    isTechnical: true,
    jobFamilies: ["IT"],
    targetLevelCode: "L4",
  },
  {
    id: "path-leadership",
    code: "PATH-LEADERSHIP",
    title: "AI for Leaders",
    audienceLevel: "L1",
    isTechnical: false,
    jobFamilies: ["MANAGEMENT"],
    targetLevelCode: "L3",
  },
];

export const OPTIONS: EngineOptions = {
  weights: DEFAULT_RECOMMENDATION_WEIGHTS,
  targetHours: 35,
  minHours: 30,
  maxHours: 40,
  pathTemplates: PATH_TEMPLATES,
};

export function learner(partial: Partial<LearnerContext> = {}): LearnerContext {
  return {
    userId: "u1",
    levelCode: "L1",
    departmentId: null,
    departmentName: null,
    jobFamily: "GENERAL",
    jobTitle: null,
    isTechnical: false,
    aiExperience: "TRIED",
    preferredLanguage: "en",
    weeklyHours: 3,
    goals: [],
    competencyScores: {},
    completedCourseIds: [],
    activeCourseIds: [],
    mandatoryCourseIds: [],
    hasAssessment: true,
    ...partial,
  };
}
